# Generated by Django 5.2 on 2025-04-16 13:35

from django.db import migrations
import phonenumbers


def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.owners_phonenumber:
            try:
                parsed_number = phonenumbers.parse(flat.owners_phonenumber, "RU")
                normalized_number = phonenumbers.format_number(parsed_number, phonenumbers.PhoneNumberFormat.E164)
                flat.owner_pure_phone = normalized_number
                flat.save()
            except phonenumbers.NumberParseException:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone_alter_flat_has_balcony'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers),
    ]
