# Generated by Django 5.2 on 2025-04-16 15:11

from django.db import migrations, models



def connect_owner_to_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        try:
            Owner.objects.get_or_create(
                owner=flat.owner,
                owners_phonenumber=flat.owners_phonenumber,
                owner_pure_phone=flat.owner_pure_phone
            )
        except Owner.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_normalize_owners_phonenumber_again2'),
    ]

    operations = [
        migrations.RunPython(connect_owner_to_flat),
    ]
