# Generated by Django 5.2 on 2025-04-16 15:31

from django.db import migrations


def link_owners_to_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.iterator():
        if not flat.owner:
            continue

        owner = Owner.objects.filter(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone
        ).first()

        if owner:
            owner.flat.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_connect_owner_to_flat'),
    ]

    operations = [
        migrations.RunPython(link_owners_to_flats),
    ]
