# Generated by Django 5.2 on 2025-04-19 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_link_owner_to_flat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
