# Generated by Django 5.2 on 2025-04-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_remove_flat_owner_remove_flat_owner_pure_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='owners_phonenumber',
        ),
    ]
