# Generated by Django 5.2 on 2025-04-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_remove_owner_owners_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phonenumber',
        ),
    ]
